#!/usr/bin/env bash

function bootstrap {
  local shome="${_bash4_home:-"$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  source "$shome/script/profile"

  pkg ensure shells/bash
  mv -f "$PKG_HOME/install/bin/bash" "$PKG_HOME/install/bin/bash4"
  rm -f "$shome/bin/bash4"
}

bootstrap
