#!/usr/bin/env bash

function bootstrap {
  local shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
  source "$shome/script/profile"

  pkg ensure shells/bash

  ln -nfs "$(which bash)" "$shome/bin/bash4"
}

bootstrap
